name: Test

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.ORG_SHARED_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test
